config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :ideas

  namespace :admin do
    resources :categories
  end
  
  root 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :name, :description, presence: true
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :ideas

  enum role: %w(default admin)

  def admin?
    role == 'admin'
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render '../../public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category successfully created"
      redirect_to admin_category_path(@category)
    else
      flash[:error] = "Could not create category"
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  # def index
  #   @ideas = current_user.ideas.all
  # end
  def index
    @ideas = current_user.ideas.all.map { |idea| IdeaPresenter.new(idea) }
  end

  def new
    @idea = current_user.ideas.new  
  end

  def show
    @idea = current_user.ideas.find(params[:id])  
  end
  
  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      flash[:success] = "That one's a zinger!"
      redirect_to ideas_path
    else
      flash[:errors] = @idea.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @idea = current_user.ideas.find(params[:id])
  end

  def update
    @idea = current_user.ideas.find(params[:id])
    if @idea.update(idea_params)
      redirect_to ideas_path
    else
      render :edit
    end
  end

  def destroy
    @idea = current_user.ideas.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:name, 
                                 :description,
                                 :category_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user #ask about this
    else
      flash[:errors] = "Invalid Login"
      render :new
    end

  end

  def destroy
    session.clear
    flash[:notice] = "Peace out, session"
    redirect_to login_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, 
                                 :password, )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<h1>Current Categories</h1>

<% @categories.each do |cat| %>
  <%= cat.name %><%= button_to "Delete Category", admin_category_path(cat), method: :delete %><br>
<% end %>
<%= link_to "New Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin/categories/show.html.erb
<h2>Category <%= @category.id %>: <%= @category.name %></h2>
<%= button_to "Remove", admin_category_path(@category), method: :delete %><br>
<%= button_to "Create New Category", new_admin_category_path, method: :get %><br>
<%= link_to "Categories Index", admin_categories_path %>

app/views/ideas/edit.html.erb
<%= form_for(@idea) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :description %><br>
    <%= f.text_field :description %><br>

  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  
    <%= f.submit 'Update' %>
<% end %>
  

app/views/ideas/index.html.erb
<h1>Your Ideas</h1>
<% @ideas.each do |idea| %>
  <p><strong><%= idea.name %>:</strong> <%= idea.description %></p>
  <p><%= link_to "Edit", edit_idea_path(idea) %></p>
  <p><%= link_to "This idea is shit", idea_path(idea), method: :delete %></p>
  <p>Tags<%= idea.category_name %> <%= idea.description %></p>
<% end %>

<%= button_to "I haz new iduh", new_idea_path, method: :get %>

app/views/ideas/new.html.erb
<%= form_for(@idea) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  
  <%= f.submit 'Create Idea' %>
<% end %>
  

app/views/ideas/show.html.erb
<h1>Your silly idea</h1>
<%= @idea.name %>
<%= @idea.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideabox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <p>Logged in as <%= current_user.username %> </p>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", login_path %>
<% end %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>